---
name: 'deploy-dev'

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@zro.dev:22/gpt-bot-dev'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
